-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_function is
port (
    a : IN STD_LOGIC;
    b : IN STD_LOGIC;
    c : OUT STD_LOGIC );
end;


architecture behav of top_function is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_function,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.956000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=4,HLS_VERSION=2020_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_1_and_gate_fu_49_ap_ready : STD_LOGIC;
    signal tmp_1_and_gate_fu_49_a : STD_LOGIC;
    signal tmp_1_and_gate_fu_49_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_not_gate_fu_57_ap_ready : STD_LOGIC;
    signal tmp_not_gate_fu_57_ap_return : STD_LOGIC_VECTOR (0 downto 0);

    component and_gate IS
    port (
        ap_ready : OUT STD_LOGIC;
        a : IN STD_LOGIC;
        b : IN STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component not_gate IS
    port (
        ap_ready : OUT STD_LOGIC;
        a : IN STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    tmp_1_and_gate_fu_49 : component and_gate
    port map (
        ap_ready => tmp_1_and_gate_fu_49_ap_ready,
        a => tmp_1_and_gate_fu_49_a,
        b => b,
        ap_return => tmp_1_and_gate_fu_49_ap_return);

    tmp_not_gate_fu_57 : component not_gate
    port map (
        ap_ready => tmp_not_gate_fu_57_ap_ready,
        a => a,
        ap_return => tmp_not_gate_fu_57_ap_return);




    c <= tmp_1_and_gate_fu_49_ap_return(0);
    tmp_1_and_gate_fu_49_a <= tmp_not_gate_fu_57_ap_return(0);
end behav;
