# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TEST_ENV_CONSTRAINS.xdc

# Block Designs: bd/chip_test_env/chip_test_env.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env || ORIG_REF_NAME==chip_test_env} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_processing_system7_0_0/chip_test_env_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_processing_system7_0_0 || ORIG_REF_NAME==chip_test_env_processing_system7_0_0} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_xbar_0/chip_test_env_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_xbar_0 || ORIG_REF_NAME==chip_test_env_xbar_0} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_ps7_0_axi_periph_0/chip_test_env_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_ps7_0_axi_periph_0 || ORIG_REF_NAME==chip_test_env_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_rst_ps7_0_100M_0/chip_test_env_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_rst_ps7_0_100M_0 || ORIG_REF_NAME==chip_test_env_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_discriminator_counter_0_0/chip_test_env_discriminator_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_discriminator_counter_0_0 || ORIG_REF_NAME==chip_test_env_discriminator_counter_0_0} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_DAC_MODULE_0_0/chip_test_env_DAC_MODULE_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_DAC_MODULE_0_0 || ORIG_REF_NAME==chip_test_env_DAC_MODULE_0_0} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_chip_fsm_controller_0_0/chip_test_env_chip_fsm_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_chip_fsm_controller_0_0 || ORIG_REF_NAME==chip_test_env_chip_fsm_controller_0_0} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_ADC_board_0_1/chip_test_env_ADC_board_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_ADC_board_0_1 || ORIG_REF_NAME==chip_test_env_ADC_board_0_1} -quiet] -quiet

# IP: bd/chip_test_env/ip/chip_test_env_auto_pc_0/chip_test_env_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chip_test_env_auto_pc_0 || ORIG_REF_NAME==chip_test_env_auto_pc_0} -quiet] -quiet

# XDC: /home/mxmont/AXI_TESTS/Chip_test_env/chip_test_env/chip_test_env.gen/sources_1/bd/chip_test_env/chip_test_env_ooc.xdc
