# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mxmont/AXI_TESTS/Chip_test_env/chip_test_env/chip_test_env.srcs/sources_1/bd/chip_test_env/ip/chip_test_env_ADC_board_0_1/chip_test_env_ADC_board_0_1.xci
# IP: The module: 'chip_test_env_ADC_board_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mxmont/AXI_TESTS/Chip_test_env/chip_test_env/chip_test_env.gen/sources_1/bd/chip_test_env/ip/chip_test_env_ADC_board_0_1/src/adc.xdc
# XDC: The top module name and the constraint reference have the same name: 'chip_test_env_ADC_board_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mxmont/AXI_TESTS/Chip_test_env/chip_test_env/chip_test_env.srcs/sources_1/bd/chip_test_env/ip/chip_test_env_ADC_board_0_1/chip_test_env_ADC_board_0_1.xci
# IP: The module: 'chip_test_env_ADC_board_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mxmont/AXI_TESTS/Chip_test_env/chip_test_env/chip_test_env.gen/sources_1/bd/chip_test_env/ip/chip_test_env_ADC_board_0_1/src/adc.xdc
# XDC: The top module name and the constraint reference have the same name: 'chip_test_env_ADC_board_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
