// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="DFF_REG_DFF_REG,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu49dr-ffvf1760-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.287000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4,HLS_SYN_LUT=2,HLS_VERSION=2020_2}" *)

module DFF_REG (
        ap_clk,
        ap_rst,
        d,
        q
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   d;
output  [2:0] q;

reg   [2:0] reg_V;
wire   [2:0] p_Result_s_fu_67_p5;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] p_Repl2_s_fu_53_p0;
wire   [0:0] tmp_fu_59_p1;
wire   [0:0] p_Repl2_s_fu_53_p2;
wire   [1:0] tmp_fu_59_p3;
reg   [0:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 reg_V = 3'd0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        reg_V <= p_Result_s_fu_67_p5;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign p_Repl2_s_fu_53_p0 = d;

assign p_Repl2_s_fu_53_p2 = (p_Repl2_s_fu_53_p0 ^ 1'd1);

assign p_Result_s_fu_67_p5 = {{tmp_fu_59_p3}, {reg_V[0:0]}};

assign q = {{tmp_fu_59_p3}, {reg_V[0:0]}};

assign tmp_fu_59_p1 = d;

assign tmp_fu_59_p3 = {{tmp_fu_59_p1}, {p_Repl2_s_fu_53_p2}};

endmodule //DFF_REG
