// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _not_gate_HH_
#define _not_gate_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct not_gate : public sc_module {
    // Port declarations 3
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > a;
    sc_out< sc_lv<1> > ap_return;


    // Module declarations
    not_gate(sc_module_name name);
    SC_HAS_PROCESS(not_gate);

    ~not_gate();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > xor_ln4_fu_12_p0;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_xor_ln4_fu_12_p0();
};

}

using namespace ap_rtl;

#endif
