// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "top_function.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool top_function::ap_const_boolean_1 = true;
const sc_logic top_function::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic top_function::ap_const_logic_0 = sc_dt::Log_0;

top_function::top_function(sc_module_name name) : sc_module(name), mVcdFile(0) {
    tmp_1_and_gate_fu_49 = new and_gate("tmp_1_and_gate_fu_49");
    tmp_1_and_gate_fu_49->ap_ready(tmp_1_and_gate_fu_49_ap_ready);
    tmp_1_and_gate_fu_49->a(tmp_1_and_gate_fu_49_a);
    tmp_1_and_gate_fu_49->b(b);
    tmp_1_and_gate_fu_49->ap_return(tmp_1_and_gate_fu_49_ap_return);
    tmp_not_gate_fu_57 = new not_gate("tmp_not_gate_fu_57");
    tmp_not_gate_fu_57->ap_ready(tmp_not_gate_fu_57_ap_ready);
    tmp_not_gate_fu_57->a(a);
    tmp_not_gate_fu_57->ap_return(tmp_not_gate_fu_57_ap_return);

    SC_METHOD(thread_c);
    sensitive << ( tmp_1_and_gate_fu_49_ap_return );

    SC_METHOD(thread_tmp_1_and_gate_fu_49_a);
    sensitive << ( tmp_not_gate_fu_57_ap_return );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "top_function_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, a, "(port)a");
    sc_trace(mVcdFile, b, "(port)b");
    sc_trace(mVcdFile, c, "(port)c");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_1_and_gate_fu_49_ap_ready, "tmp_1_and_gate_fu_49_ap_ready");
    sc_trace(mVcdFile, tmp_1_and_gate_fu_49_a, "tmp_1_and_gate_fu_49_a");
    sc_trace(mVcdFile, tmp_1_and_gate_fu_49_ap_return, "tmp_1_and_gate_fu_49_ap_return");
    sc_trace(mVcdFile, tmp_not_gate_fu_57_ap_ready, "tmp_not_gate_fu_57_ap_ready");
    sc_trace(mVcdFile, tmp_not_gate_fu_57_ap_return, "tmp_not_gate_fu_57_ap_return");
#endif

    }
    mHdltvinHandle.open("top_function.hdltvin.dat");
    mHdltvoutHandle.open("top_function.hdltvout.dat");
}

top_function::~top_function() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete tmp_1_and_gate_fu_49;
    delete tmp_not_gate_fu_57;
}

void top_function::thread_c() {
    c =  (sc_logic) (tmp_1_and_gate_fu_49_ap_return.read()[0]);
}

void top_function::thread_tmp_1_and_gate_fu_49_a() {
    tmp_1_and_gate_fu_49_a =  (sc_logic) (tmp_not_gate_fu_57_ap_return.read()[0]);
}

void top_function::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"a\" :  \"" << a.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b\" :  \"" << b.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"c\" :  \"" << c.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

