// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _top_function_HH_
#define _top_function_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "and_gate.h"
#include "not_gate.h"

namespace ap_rtl {

struct top_function : public sc_module {
    // Port declarations 3
    sc_in< sc_logic > a;
    sc_in< sc_logic > b;
    sc_out< sc_logic > c;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    top_function(sc_module_name name);
    SC_HAS_PROCESS(top_function);

    ~top_function();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    and_gate* tmp_1_and_gate_fu_49;
    not_gate* tmp_not_gate_fu_57;
    sc_signal< sc_logic > tmp_1_and_gate_fu_49_ap_ready;
    sc_signal< sc_logic > tmp_1_and_gate_fu_49_a;
    sc_signal< sc_lv<1> > tmp_1_and_gate_fu_49_ap_return;
    sc_signal< sc_logic > tmp_not_gate_fu_57_ap_ready;
    sc_signal< sc_lv<1> > tmp_not_gate_fu_57_ap_return;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_c();
    void thread_tmp_1_and_gate_fu_49_a();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
